package dk.skat.dmr.proxies;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2018-10-08T16:00:30.008+02:00
 * Generated source version: 3.1.9
 * 
 */
@WebServiceClient(name = "USImportoerService", 
                  wsdlLocation = "file:/C:/Data/GitHub/dmr/dmr-b2b-ws-sample-client-java/src/main/resources/wsdls/USImportoerService.wsdl",
                  targetNamespace = "http://skat.dk/dmr/2007/05/31/") 
public class USImportoerService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://skat.dk/dmr/2007/05/31/", "USImportoerService");
    public final static QName Port = new QName("http://skat.dk/dmr/2007/05/31/", "Port");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Data/GitHub/dmr/dmr-b2b-ws-sample-client-java/src/main/resources/wsdls/USImportoerService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(USImportoerService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Data/GitHub/dmr/dmr-b2b-ws-sample-client-java/src/main/resources/wsdls/USImportoerService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public USImportoerService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public USImportoerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public USImportoerService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public USImportoerService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public USImportoerService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public USImportoerService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns USImportoerServiceType
     */
    @WebEndpoint(name = "Port")
    public USImportoerServiceType getPort() {
        return super.getPort(Port, USImportoerServiceType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns USImportoerServiceType
     */
    @WebEndpoint(name = "Port")
    public USImportoerServiceType getPort(WebServiceFeature... features) {
        return super.getPort(Port, USImportoerServiceType.class, features);
    }

}
