package dk.skat.dmr.proxies;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2018-10-08T16:00:29.994+02:00
 * Generated source version: 3.1.9
 * 
 */
@WebService(targetNamespace = "http://skat.dk/dmr/2007/05/31/", name = "USImportoerServiceType")
@XmlSeeAlso({dk.oio.rep.skat_dk.basis.kontekst.xml.schemas._2006._09._01.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface USImportoerServiceType {

    @WebMethod(action = "getUSTilladelseTypeListeHent")
    @WebResult(name = "USTilladelseTypeListeHent_O", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    public USTilladelseTypeListeHentO getUSTilladelseTypeListeHent(
        @WebParam(partName = "Request", name = "USTilladelseTypeListeHent_I", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        USTilladelseTypeListeHentI request
    );

    @WebMethod(action = "getUSKoeretoejUdstyrTypeListeHent")
    @WebResult(name = "USKoeretoejUdstyrTypeListeHent_O", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    public USKoeretoejUdstyrTypeListeHentO getUSKoeretoejUdstyrTypeListeHent(
        @WebParam(partName = "Request", name = "USKoeretoejUdstyrTypeListeHent_I", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        USKoeretoejUdstyrTypeListeHentI request
    );

    @WebMethod(action = "getUSDispensationTypeListeHent")
    @WebResult(name = "USDispensationTypeListeHent_O", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    public USDispensationTypeListeHentO getUSDispensationTypeListeHent(
        @WebParam(partName = "Request", name = "USDispensationTypeListeHent_I", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        USDispensationTypeListeHentI request
    );

    @WebMethod(action = "getUSKoeretoejArtListeHent")
    @WebResult(name = "USKoeretoejArtListeHent_O", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    public USKoeretoejArtListeHentO getUSKoeretoejArtListeHent(
        @WebParam(partName = "Request", name = "USKoeretoejArtListeHent_I", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        USKoeretoejArtListeHentI request
    );

    @WebMethod(action = "getUSKoeretoejOprettelseAnnuller")
    @WebResult(name = "USKoeretoejOprettelseAnnuller_O", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    public USKoeretoejOprettelseAnnullerO getUSKoeretoejOprettelseAnnuller(
        @WebParam(partName = "Request", name = "USKoeretoejOprettelseAnnuller_I", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        USKoeretoejOprettelseAnnullerI request
    );

    @WebMethod(action = "getUSFarveTypeListeHent")
    @WebResult(name = "USFarveTypeListeHent_O", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    public USFarveTypeListeHentO getUSFarveTypeListeHent(
        @WebParam(partName = "Request", name = "USFarveTypeListeHent_I", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        USFarveTypeListeHentI request
    );

    @WebMethod(action = "getUSKoeretoejRegistreringHent")
    @WebResult(name = "USKoeretoejRegistreringHent_O", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    public USKoeretoejRegistreringHentO getUSKoeretoejRegistreringHent(
        @WebParam(partName = "Request", name = "USKoeretoejRegistreringHent_I", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        USKoeretoejRegistreringHentI request
    );

    @WebMethod(action = "getUSUkompletKoeretoejOpret")
    @WebResult(name = "USUkompletKoeretoejOpret_O", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    public USUkompletKoeretoejOpretO getUSUkompletKoeretoejOpret(
        @WebParam(partName = "Request", name = "USUkompletKoeretoejOpret_I", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        USUkompletKoeretoejOpretI request
    );

    @WebMethod(action = "getKompenserTrans")
    @WebResult(name = "KompenserTransSvar", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    public KompenserTransSvarType getKompenserTrans(
        @WebParam(partName = "Request", name = "KompenserTrans", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        KompenserTransType request
    );

    @WebMethod(action = "getUSKoeretoejBetegnelseOpret")
    @WebResult(name = "USKoeretoejBetegnelseOpret_O", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    public USKoeretoejBetegnelseOpretO getUSKoeretoejBetegnelseOpret(
        @WebParam(partName = "Request", name = "USKoeretoejBetegnelseOpret_I", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        USKoeretoejBetegnelseOpretI request
    );

    @WebMethod(action = "getUSKoeretoejCoCOpret")
    @WebResult(name = "USKoeretoejCoCOpret_O", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    public USKoeretoejCoCOpretO getUSKoeretoejCoCOpret(
        @WebParam(partName = "Request", name = "USKoeretoejCoCOpret_I", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        USKoeretoejCoCOpretI request
    );

    @WebMethod(action = "getUSKoeretoejAnvendelseListeHent")
    @WebResult(name = "USKoeretoejAnvendelseListeHent_O", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    public USKoeretoejAnvendelseListeHentO getUSKoeretoejAnvendelseListeHent(
        @WebParam(partName = "Request", name = "USKoeretoejAnvendelseListeHent_I", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        USKoeretoejAnvendelseListeHentI request
    );

    @WebMethod(action = "getUSKoeretoejTypeAttestOpret")
    @WebResult(name = "USKoeretoejTypeAttestOpret_O", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    public USKoeretoejTypeAttestOpretO getUSKoeretoejTypeAttestOpret(
        @WebParam(partName = "Request", name = "USKoeretoejTypeAttestOpret_I", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        USKoeretoejTypeAttestOpretI request
    );

    @WebMethod(action = "getUSKoeretoejArtAnvendelseListeHent")
    @WebResult(name = "USKoeretoejArtAnvendelseListeHent_O", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    public USKoeretoejArtAnvendelseListeHentO getUSKoeretoejArtAnvendelseListeHent(
        @WebParam(partName = "Request", name = "USKoeretoejArtAnvendelseListeHent_I", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        USKoeretoejArtAnvendelseListeHentI request
    );

    @WebMethod(action = "getUSKoeretoejErklaeringOpret")
    @WebResult(name = "USKoeretoejErklaeringOpret_O", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    public USKoeretoejErklaeringOpretO getUSKoeretoejErklaeringOpret(
        @WebParam(partName = "Request", name = "USKoeretoejErklaeringOpret_I", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        USKoeretoejErklaeringOpretI request
    );

    @WebMethod(action = "getUSKoeretoejTekniskDataHent")
    @WebResult(name = "USKoeretoejTekniskDataHent_O", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    public USKoeretoejTekniskDataHentO getUSKoeretoejTekniskDataHent(
        @WebParam(partName = "Request", name = "USKoeretoejTekniskDataHent_I", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        USKoeretoejTekniskDataHentI request
    );

    @WebMethod(action = "getUSKarrosseriTypeListeHent")
    @WebResult(name = "USKarrosseriTypeListeHent_O", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    public USKarrosseriTypeListeHentO getUSKarrosseriTypeListeHent(
        @WebParam(partName = "Request", name = "USKarrosseriTypeListeHent_I", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        USKarrosseriTypeListeHentI request
    );

    @WebMethod(action = "getUSKoeretoejBlokeringAarsagTypeListeHent")
    @WebResult(name = "USKoeretoejBlokeringAarsagTypeListeHent_O", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    public USKoeretoejBlokeringAarsagTypeListeHentO getUSKoeretoejBlokeringAarsagTypeListeHent(
        @WebParam(partName = "Request", name = "USKoeretoejBlokeringAarsagTypeListeHent_I", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        USKoeretoejBlokeringAarsagTypeListeHentI request
    );

    @WebMethod(action = "getUSSupplerendeKarrosseriTypeListeHent")
    @WebResult(name = "USSupplerendeKarrosseriTypeListeHent_O", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    public USSupplerendeKarrosseriTypeListeHentO getUSSupplerendeKarrosseriTypeListeHent(
        @WebParam(partName = "Request", name = "USSupplerendeKarrosseriTypeListeHent_I", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        USSupplerendeKarrosseriTypeListeHentI request
    );

    @WebMethod(action = "getUSDrivkraftTypeListeHent")
    @WebResult(name = "USDrivkraftTypeListeHent_O", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    public USDrivkraftTypeListeHentO getUSDrivkraftTypeListeHent(
        @WebParam(partName = "Request", name = "USDrivkraftTypeListeHent_I", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        USDrivkraftTypeListeHentI request
    );

    @WebMethod(action = "getUSNormTypeListeHent")
    @WebResult(name = "USNormTypeListeHent_O", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    public USNormTypeListeHentO getUSNormTypeListeHent(
        @WebParam(partName = "Request", name = "USNormTypeListeHent_I", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        USNormTypeListeHentI request
    );

    @WebMethod(action = "getUSKoeretoejBetegnelseHierarkiListeHent")
    @WebResult(name = "USKoeretoejBetegnelseHierarkiListeHent_O", targetNamespace = "http://skat.dk/dmr/2007/05/31/", partName = "Response")
    public USKoeretoejBetegnelseHierarkiListeHentO getUSKoeretoejBetegnelseHierarkiListeHent(
        @WebParam(partName = "Request", name = "USKoeretoejBetegnelseHierarkiListeHent_I", targetNamespace = "http://skat.dk/dmr/2007/05/31/")
        USKoeretoejBetegnelseHierarkiListeHentI request
    );
}
